# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics')),
                ('office_address', models.CharField(blank=True, max_length=250, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(choices=[('ast', 'Assistant Professor'), ('asc', 'Associate Professor'), ('pro', 'Professor'), ('hod', 'Professor and Head'), ('hon', 'Honarary Professor'), ('vst', 'Visiting Professor')], default='ast', max_length=4)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('funding_agency', models.CharField(max_length=200, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('co_investigator', models.ManyToManyField(related_name='copi', to=settings.AUTH_USER_MODEL)),
                ('principal_investigator', models.ManyToManyField(related_name='pi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recognitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('given_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rollno', models.IntegerField()),
                ('program', models.CharField(choices=[('bt', 'BTech'), ('mt', 'MTech'), ('ph', 'PhD'), ('ms', 'MSc'), ('bd', 'BDes'), ('md', 'MDes')], max_length=2)),
                ('joining_year', models.IntegerField()),
                ('passing_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.student')),
                ('supervisors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(to='faculty.student'),
        ),
    ]
