# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('department_cover', models.ImageField(blank=True, null=True, upload_to='department_covers')),
                ('department_logo', models.ImageField(blank=True, null=True, upload_to='department_logos')),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics')),
                ('office_address', models.CharField(blank=True, max_length=250, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(choices=[('ast', 'Assistant Professor'), ('asc', 'Associate Professor'), ('pro', 'Professor'), ('hod', 'Professor and Head'), ('hon', 'Honarary Professor'), ('vst', 'Visiting Professor')], default='ast', max_length=4)),
                ('research_interest', models.CharField(blank=True, max_length=1000, null=True)),
                ('primary_research_group', models.CharField(blank=True, max_length=1000, null=True)),
                ('education_phd', models.CharField(blank=True, max_length=1000, null=True)),
                ('education_masters', models.CharField(blank=True, max_length=1000, null=True)),
                ('education_batchelor', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('principal_investigator', models.CharField(max_length=500)),
                ('co_investigator', models.CharField(blank=True, max_length=500, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2017)])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2017)])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=25000)),
                ('published_in', models.CharField(max_length=500)),
                ('time_published', models.CharField(blank=True, max_length=50, null=True)),
                ('contributors', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('given_by', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=25000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rollno', models.IntegerField()),
                ('program', models.CharField(choices=[('bt', 'BTech'), ('mt', 'MTech'), ('ph', 'PhD'), ('ms', 'MSc'), ('bd', 'BDes'), ('md', 'MDes')], max_length=2)),
                ('joining_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1994), django.core.validators.MaxValueValidator(2017)])),
                ('passing_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1994), django.core.validators.MaxValueValidator(2017)])),
                ('thesis_title', models.CharField(max_length=500)),
                ('thesis_description', models.CharField(blank=True, max_length=25000, null=True)),
                ('thesis_supervisors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_title', models.CharField(max_length=500)),
                ('academic_year_start', models.IntegerField(validators=[django.core.validators.MinValueValidator(1994), django.core.validators.MinValueValidator(2017)])),
                ('semester', models.CharField(choices=[('even', 'Even Semester'), ('odd', 'Odd Semester')], max_length=4)),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workexperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('organisation', models.CharField(max_length=2000)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2017)])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2017)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(to='faculty.student'),
        ),
    ]
